sudo: false
language:
- python
install:
- pip install -r requirements.txt
script:
- coverage run manage.py test
deploy:
  provider: heroku
  api_key:
    secure: MHN4ohw6u0Fvqhjotax1ro7WOslQPEIOK2jLvLGULz0A2BRG2HcfuqpyNHBo52otyZ600OkhKobRIjlp8xGqJtANNv0pZBp0jV8xNk4beGCEcs/wogG4DN0lvVZ5O+6ilO6qfaCvHZ9NQOgoEdEz1yjRu4ZHtUnBQ0jrykJ9+fkk/hBoRS3PqSvvUfobtj3yHGBO7qZkA541hyapfzmA3vJKJ45Z/Xh4i0XSV8Mx67K9HIUwXCE9mltOB6gcoxtqKV9sMtEpvCBLG73mnFqThwhrub2321cNvpZOTHf05mSEaNO3/UcXCUG/9bGdm+GakJLVrZ8QZjAXbrnkci/9qxkF034POUhlv7jbMkawGjoToVgyNU58V1N60aDD/ziOuxZDpVhs5Gr4dUr/vbiLGsR2WUr7ZhPFC79+Fq4rhBtPZ3ggZUqjuruY0ZNUuOD8ZyDcUm00QwiNVTAkuDj3eV/gSZg6mkZOB+fM3WKM18FmsmEq/jyv3Hmv3Teas1GP/zCY7vVVUvFhAV/E0AX/B6JzPsc69hg0hio84YcyMJCrUxgTOFwWhtZW1phfocQ1L7DltMnHfyw3NCD16/7uZFvOYTB1BaqyKJhjLggkcS0rG+0zUxYSZBOvz5tObCtsQFzeoWeRkti7c+iSM5fRXsa2Vz74LTlIYRhgZfCY4QA=
  app: eventus-master
  on:
    repo: evangilo/eventus
